// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF0Ruc1p0jgmnnYz1bBblaYz120YaijB8',
    appId: '1:98588469717:web:6d870fc624f39fdfe7355c',
    messagingSenderId: '98588469717',
    projectId: 'equipo-estrella-damm',
    authDomain: 'equipo-estrella-damm.firebaseapp.com',
    storageBucket: 'equipo-estrella-damm.appspot.com',
    measurementId: 'G-28BBS78EWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUrvLUHSc2iSgXHpQE6uROveq60c6YJP8',
    appId: '1:98588469717:android:b9aa7a8c534dd184e7355c',
    messagingSenderId: '98588469717',
    projectId: 'equipo-estrella-damm',
    storageBucket: 'equipo-estrella-damm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVaFEwW8a9igRo8xBPZ0PjOfdvzU8AbD4',
    appId: '1:98588469717:ios:550ee1b7a0904271e7355c',
    messagingSenderId: '98588469717',
    projectId: 'equipo-estrella-damm',
    storageBucket: 'equipo-estrella-damm.appspot.com',
    iosBundleId: 'com.example.equipoEstrella',
  );
}
