// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLfqTTKtzqL6J7I3AAnrO0mxZEMi-q9Ps',
    appId: '1:778498971446:web:ff23b9937e6a2132dc8597',
    messagingSenderId: '778498971446',
    projectId: 'equipo-estrella',
    authDomain: 'equipo-estrella.firebaseapp.com',
    storageBucket: 'equipo-estrella.appspot.com',
    measurementId: 'G-Z1F8670Q25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2sh2pNd-P6gi1T1S19jE-HLfjWyOBml4',
    appId: '1:778498971446:android:87050251092fb7fddc8597',
    messagingSenderId: '778498971446',
    projectId: 'equipo-estrella',
    storageBucket: 'equipo-estrella.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkAFDcyck42KxIJ4AbsR1rLLzIw_7Bh7I',
    appId: '1:778498971446:ios:83303f15939bd380dc8597',
    messagingSenderId: '778498971446',
    projectId: 'equipo-estrella',
    storageBucket: 'equipo-estrella.appspot.com',
    iosBundleId: 'com.example.equipoEstrella',
  );
}
